version: "3"
services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command:
      - start-dev
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      KC_DB: mysql
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_PROXY_HEADERS: xforwarded
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
    volumes:
      - ./target/vp-kuljetus-transport-management-driver-card-keycloak-auth-provider-1.0.0-SNAPSHOT-jar-with-dependencies.jar:/opt/keycloak/providers/driver-card-keycloak-auth-provider.jar
  vehicle-management-service:
    build:
      context: ../vp-kuljetus-vehicle-management-service-api
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8280:8080
    depends_on:
      - mysql
      - keycloak
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/vehicle-management-service?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      QUARKUS_DATASOURCE_PASSWORD: vehicle-management-service
      QUARKUS_DATASOURCE_USERNAME: vehicle-management-service
      QUARKUS_DATASOURCE_REACTIVE_URL: mysql://mysql:3306/vehicle-management-service?useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
      QUARKUS_HTTP_CORS_ORIGINS: "*"
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/auth/realms/vp
      QUARKUS_OIDC_CLIENT_ID: vehicle-management-service
      QUARKUS_OIDC_CREDENTIALS_SECRET: 3e3e3e3e-3e3e-3e3e-3e3e-3e3e3e3e3e3e
      VP_ENV: development
      VP_VEHICLEMANAGEMENT_TELEMATICS_APIKEY: 3e3e3e3e-3e3e-3e3e-3e3e-3e3e3e3e3e3e
      QUARKUS_OIDC_CONNECTION_DELAY: 10s

volumes:
  db_data: {}
