name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Resolve base version
      run: |
        echo "BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout|cut -d'-' -f1)" >> $GITHUB_ENV

    - name: Bump version to master version
      run: mvn versions:set -DnewVersion=${{ env.BASE_VERSION }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
