name: Publish Package

on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: ${{github.event.inputs.id}}
      run: echo run identifier ${{ inputs.id }}
      
    - uses: actions/checkout@v3

    - name: Merge develop -> master
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: develop
        target_branch: master
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Resolve base version
      run: |
        echo "BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout|cut -d'-' -f1)" >> $GITHUB_ENV

    - name: Bump version to master version
      run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ env.BASE_VERSION }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Push version changes to master
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master